### ISSUE TITLE
[DB] DB의 트랜잭션 조작어(TCL)에 대해 설명해주세요

### ISSUE THREAD

**Issue by sw0501** [CSSAFTUDY/CS_STUDY#3]
TCL
Transaction Control Language

COMMIT / SAVEPOINT / ROLLBACK / TRUNCATE

COMMIT :
하나의 트랜잭션을 물리적인 데이터베이스에 적용하는 작업으로, 마지막 COMMIT 시점 이후 실행한 트랜잭션 결과를 데이터베이스에 영구적으로 저장한다.
그러므로 마지막으로 COMMIT한 시점까지만 ROLLBACK이 가능하다.
COMMIT;

SAVEPOINT :
SAVEPOINT를 지정하면, ROLLBACK시 해당 지정 위치로 복원이 가능하여 SAVEPOINT 명령어로 지점을 지정, ROLLBACK 명령어로 복원한다.
SAVEPOINT SV1;

ROLLBACK :
데이터의 수정, 삭제, 삽입 등의 작업을 한 후 원래의 상태로 되돌릴 때 사용하는 작업이다.
COMMIT 이후에는 ROLLBACK하더라도 이전으로 돌아갈 수 없다.
ROLLBACK;
ROLLBACK TO SV1;

TRUNCATE (DDL)
지정된 테이블의 모든 데이터를 삭제한다.
자동으로 COMMIT 되므로 ROLLBACK 할 수 없다.
TRUNCATE TABLE table_name;

**Comment by ParkRang** [comment]
이거 제가 잘못 썼는데 TRUNCATE -> DDL임...
예시로 넣다가 TCL로 넣어버림...

**Comment by sw0501** [comment]
수정했습니다
