### ISSUE TITLE
[Database] 2/28 추가 질문 

### ISSUE THREAD

**Issue by bsyun0571** [CSSAFTUDY/CS_STUDY#31]
### SQL

- grant를 통해 admin 권한을 줄 수 있는가?
- limit이 모든 SQL에서 작동하는가?
- select 할 때도 transaction을 해주는게 좋은가?

### ERD

- ER Model → ERD(개념적 모델링에서 논리적 모델링으로 넘어가는 과정에서 DBMS를 정하는가?)

### Transaction

- savepoint가 마지막 commit 시점과 항상 동일한가?
- Rollback의 동작 방식에 대해서

**Comment by ParkRang** [comment]
SQL
1. 가능
2. MySQL과 PostgreSQL에서만 가능 - 표준 SQL이 아님
3. 해주는 것이 좋다 / 할 필요가 없다 의견이 갈림
REPEATABLE READ 격리 수준에서는 데이터 변경 후 커밋 이후에도 동일한 결과를 보게 되기에, read committed일 때는 특정 트랜잭션 내에서 A 데이터를 조회하고 나서 다른 트랜잭션에서 해당 데이터를 변경하고 A 트랜잭션에서 다시 해당 데이터를 조회하게 되면 변경된 데이터가 조회되기에 필요하다. / 굳이 사용할 필요가 없다.( 조회만 한다면 트랜잭션으로 묶일 이유가 없다. )
