### ISSUE TITLE
[NoSQL] NoSQL 데이터베이스 유형 4가지와 특징을 설명하시오

### ISSUE THREAD

**Issue by sw0501** [CSSAFTUDY/CS_STUDY#37]
### NoSQL 데이터베이스 유형 4가지와 장/단점을 설명하시오
- #### Key-Value 데이터베이스 ex) Redis
    - Key와 Value로만 이루어져 있어서 읽기 쓰기가 매우 빠름
    - 조인과 같은 복잡한 조회 연산을 지원하지 않음
- #### Big Table 데이터베이스 ex) Cassandra
    - Key-Value 데이터베이스와 동일한 저장방식 사용
    - 내부적으로 Key를 정렬해서 데이터를 제공 (선착순, 날짜별 데이터 제공 시 유리)
- #### Document 데이터베이스 ex) MongoDB
    - Key-Value 데이터베이스의 확장 버전
    - Value에 Document 타입을 저장하여 복잡한 데이터 구조 표현 가능ex) JSON, XML, YAML 등
    - Document_id에 대한 인덱스가 자동으로 생성
    - Sorting, Join, Grouping 등 복잡한 쿼리 연산 지원
- #### Graph 데이터베이스 ex) neo4j
    - node들과 Relationship으로 구성
    - Key-Value 방식이며 모든 노드들은 서로 연결되어 있음
    - Relationship에는 direction, type, start node, end node 등이 있음

**Comment by infikei** [comment]
column-family 데이터베이스와 big Table 데이터 베이스는 같다고 볼 수 있나요?

**Comment by sw0501** [comment]
> column-family 데이터베이스와 big Table 데이터 베이스는 같다고 볼 수 있나요? - 진우

Big Table 데이터베이스가 column-family 데이터 모델을 사용했다고 합니다.
출처 : https://pinopino.tistory.com/entry/%084-NoSQL
