### ISSUE TITLE
[NoSQL] NoSQL과 SQL의 차이를 설명하세요

### ISSUE THREAD

**Issue by ParkRang** [CSSAFTUDY/CS_STUDY#38]
### 질문 내용

비관계형 데이터베이스(NoSQL)
- 비관계형 데이터베이스(NoSQL 데이터베이스)은 더 유연하며 SQL과 같은 엄격한 구조가 필요하지 않음.
- 행, 테이블, 키가 포함되지 않으며 저장하는 데이터 유형에 따라 스토리지 모델을 사용함.

관계형 데이터베이스(SQL)
- 관계형 데이터베이스는 구조화 쿼리 언어(SQL)를 사용하여 데이터를 저장하고 검색함.
- RDBMS라고도 하며 데이터를 행과 테이블에 각각 저장한다.

-----------------------------------
![image](https://github.com/CSSAFTUDY/CS_STUDY/assets/104675938/e85bb147-22b6-4486-91b9-b39c77fbea27)

-----------------------------------

RDBMS는 구조화된 쿼리 언어를 사용하며, 데이터를 정의하고 조작하기 위해 사전 정의된 스키마가 있고, SQL은 사용 가능한 쿼리 언어 중 다양하고 널리 사용되는 언어이므로 복잡한 쿼리에 적합하며, 사전 정의된 스키마를 사용하여 데이터 구조를 결정해야 하기에 모든 데이터는 동일한 구조를 따른다. 데이터 구조를 변경하려는 경우 수행하는 것이 어렵다.

NoSQL의 경우 비정형 데이터에 대한 동적 스키마가 있으며 데이터가 다양한 방식으로 저장된다. 데이터에 대한 컬럼 지향, 문서 지향, 그래프 기반, keyValue 등을 사용할 수 있다. 이러한 유연성을 통해 구조를 정의하지 않고도 문서를 생성할 수 있으며 각 문서는 고유한 구조를 가질 수 있다. 구문 또한 데이터베이스마다 다를 수 있다.

------------------------------------

SQL 데이터베이스 시스템은 다중행 트랜잭션에 더 효과적이고, NoSQL은 문서나 JSON과 같은 비정형 데이터에 더 효과적이다. 결합 작업이 있는 애플리케이션에 사용되는 경우가 있으며, SQL 스키마로 ACID 속성을 설정하고 데이터 호환성을 높일 수 있고, 작업 완료에 필요한 데이터를 찾을 때에도 유용하다.

NoSQL 데이터베이스는 결합 작업이 없는 동적 데이터를 다루는 애플리케이션에 사용되는 경우가 있다. 비즈니스에 영향을 미치지 않는 정도의 결손 데이터 세트가 있는 애플리케이션에도 적합하다.

**Comment by PARKSEGUN** [comment]
NoSQL의 비정형 데이터에 대한 동적 스키마는 데이터를 저장할때 정의되는 건가요?

**Comment by ParkRang** [comment]
> NoSQL의 비정형 데이터에 대한 동적 스키마는 데이터를 저장할때 정의되는 건가요?

네
